GET http://localhost:8108/api/l1/

###

GET http://localhost:8108/api/l1/param/name/Tiago

###

GET http://localhost:8108/api/l1/params/name/Tiago/age/18/club/Porto

###

GET http://localhost:8108/api/l1/query?name=Filipa&age=41&club=Benfica

###

GET http://localhost:8108/api/l1/headers
Name: Marcelo
Age: 76
Club: Braga

###

GET http://localhost:8108/api/l1/structured/name/Tiago/age/18/club/Porto